app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /app

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /
 
demo:
    resource: "@DemoBundle/Resources/config/routing.yml"
    prefix:   /
    

    